<div class="well sidebar-nav">
    <ul class="nav nav-list">
        <li><a href="<?php echo $this->baseUrl(); ?>/quem-somos"><i class="icon-home"></i> Quem Somos</a></li>
        <li><a href="<?php echo $this->baseUrl(); ?>/advogados"><i class="icon-user"></i> Advogados</a></li>
        <li><a href="<?php echo $this->baseUrl(); ?>/atuacao"><i class="icon-globe"></i> Atuação</a></li>
        <li><a href="<?php echo $this->baseUrl(); ?>/doadores"><i class="icon-comment"></i> Alguns Doadores</a></li>
        <li><a href="<?php echo $this->baseUrl(); ?>/contato"><i class="icon-envelope"></i> Contato</a></li>
        <li><a href="<?php echo $this->baseUrl(); ?>/auth/login"><i class="icon-lock"></i> Acesso restrito</a></li>
    </ul>
</div>