<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <title>SERTE - Sociedade Espírita de Recuperação, Trabalho e Educação</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="<?php echo $this->baseUrl(); ?>/public/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    <link href="<?php echo $this->baseUrl(); ?>/public/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl(); ?>/public/css/style.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <script src="<?php echo $this->baseUrl(); ?>/public/js/jquery/jquery-1.9.1.min.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/public/js/jquery/jquery.validate.min.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/public/js/bootstrap.min.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/public/js/jquery/jquery.maskedinput.min.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/public/js/jquery/jquery.maskMoney.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/public/js/jquery/jquery.message.js"></script>
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">SERTE - Sociedade Espírita de Recuperação, Trabalho e Educação</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
            </p>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row-fluid">
          <?=$this->render('menusistema.phtml'); ?>
        <div class="span9">
          <?= $this->layout()->content ?>
        </div>
      </div>
    </div>
	<br />
    <div class="navbar navbar-fixed-bottom">
        <div class="navbar-inner">
            <div style="text-align: center; color: white;">
                SERTE - Sociedade Espírita de Recuperação, Trabalho e Educação<br>
                Rua Allan Kardec, 142 - Cx. Postal 664, Centro - CEP 88.025-100 - Florianópolis - SC Fone (48) 3228-2285<br>
                <small>Copyright&copy; <?php echo date('Y'); ?> SERTE - Sociedade Espírita de Recuperação, Trabalho e Educação</small>
            </div>
        </div>
    </div>
  </body>
</html>