<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <title>SERTE - Sociedade Espírita de Recuperação, Trabalho e Educação</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="<?php echo $this->baseUrl(); ?>/public/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    <link href="<?php echo $this->baseUrl(); ?>/public/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-35184277-5', 'brasilebrasiladv.com.br');
        ga('send', 'pageview');
	</script>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
  		<div class="navbar-inner pull-right">
            <a class="brand" href="#">&nbsp;&nbsp;&nbsp;SERTE - Sociedade Espírita de Recuperação, Trabalho e Educação</a>
        </div>
      </div>
    </div>

    <div class="container-fluid">
    	<!--
    	<div style="background-color: #dedede; text-align: center;">
            container
    	</div>

    	<br>
    	 -->


      <div class="row-fluid">
        <div class="span3">
        	<p>
        		<object type="application/x-shockwave-flash" data="<?php echo $this->serverUrl().$this->baseUrl(); ?>/public/img/logo.swf" width="257" height="79" id="myContent" style="visibility: visible;"><param name="wmode" value="transparent"></object>
        	            </p>
            <? //=$this->render('menu.phtml'); ?>
        </div>

        <div class="span9">
          <?= $this->layout()->content ?>

        </div><!--/span-->
      </div><!--/row-->

    </div><!--/.fluid-container-->

	 <div class="navbar navbar-fixed-bottom">
	 <!--
	  -->
	 	<div class="navbar-inner">
    	 	<div style="text-align: center; color: white;">
                SERTE - Sociedade Espírita de Recuperação, Trabalho e Educação<br>
                Rua Allan Kardec, 142 - Cx. Postal 664, Centro - CEP 88.025-100 - Florianópolis - SC Fone (48) 3228-2285<br>
                <small>Copyright&copy; <?php echo date('Y'); ?> SERTE - Sociedade Espírita de Recuperação, Trabalho e Educação</small>
    	 	</div>
	 	</div>
    </div>




    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="<?php echo $this->baseUrl(); ?>/public/js/jquery/jquery-1.9.1.min.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/public/js/bootstrap.min.js"></script>
  </body>
</html>